krun: return dlerror string when library is not found
krun returns incomplete error without this patch which is difficult to debug
```console
Error: OCI runtime error: /home/crun/krun: failed to open library `libkrun.so.1` and `libkrun-sev.so.1` for krun_config
```

after patch
```console
Error: /home/ar/work/crun/krun: failed to open library `libkrun.so.1` and `libkrun-sev.so.1` for krun_config: libkrun-sev.so.1: cannot open shared object file: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

Signed-off-by: flouthoc <flouthoc.git@gmail.com>