cgroup: improve error with unavailable errors
if a file could not be written on cgroup v2, detect whether the
required controller is enabled in the cgroup.  If it is not present,
give a better error message to the user.

Example:

$ podman run --rm --cpus 1 alpine echo hello
Error: the requested cgroup controller `cpu` is not available: OCI runtime error

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>