Fix python call to `libcrun_get_verbosity`
Fixes erroneous call with an unused argument to a 0-argument function.
Current call fails with GCC 15.1:
```
python/crun_python.c: In function 'get_verbosity':
python/crun_python.c:461:27: error: too many arguments to function 'libcrun_get_verbosity'; expected 0, have 1
  461 |   return PyLong_FromLong (libcrun_get_verbosity (verbosity));
      |                           ^~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~
In file included from /home/user/.cache/yay/crun-krun/src/crun/src/libcrun/container.h:24:
/home/user/.cache/yay/crun-krun/src/crun/src/libcrun/error.h:109:20: note: declared here
  109 | LIBCRUN_PUBLIC int libcrun_get_verbosity ();
      |                    ^~~~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Sebastian Gsänger <8004308+sgsaenger@users.noreply.github.com>