handlers: Fix -Werror=unused-parameter build error for spin
Fix the build with "./configure CFLAGS='-Wall -Wextra -Werror' --with-spin=yes"

	src/libcrun/handlers/spin.c: In function 'spin_load':
	src/libcrun/handlers/spin.c:55:19: error: unused parameter 'cookie' [-Werror=unused-parameter]
	   55 | spin_load (void **cookie, libcrun_error_t *err)
	      |            ~~~~~~~^~~~~~
	src/libcrun/handlers/spin.c: In function 'spin_unload':
	src/libcrun/handlers/spin.c:93:20: error: unused parameter 'cookie' [-Werror=unused-parameter]
	   93 | spin_unload (void *cookie, libcrun_error_t *err)
	      |              ~~~~~~^~~~~~
	src/libcrun/handlers/spin.c:93:45: error: unused parameter 'err' [-Werror=unused-parameter]
	   93 | spin_unload (void *cookie, libcrun_error_t *err)
	      |                            ~~~~~~~~~~~~~~~~~^~~
	cc1: all warnings being treated as errors

Signed-off-by: Haiyue Wang <haiyue.wang@intel.com>