cgroup: silence a maybe-uninitialized warning
period_len is only read when period_str is not NULL, and the two are set
together, but gcc does not make that connection once the sanitizers change
what it inlines, and --enable-werror then fails the build:

  src/libcrun/cgroup-resources.c:1106:21: error: 'period_len' may be used
  uninitialized [-Werror=maybe-uninitialized]

Initialize it.

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>